version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: info902
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  assistant-backend:
    build:
      context: ./Backend
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/info902
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  assistant-frontend:
    build:
      context: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - assistant-backend
    restart: always
